language: ruby

before_script:
 - awk 'BEGIN{for (i=1;i<=10000000;i++) print (i%5?"miss":"hit"),i,"  third\t \tfourth"}' > ./input

script: 
  - for s in ./awk/*.awk; do echo Testing $s; done
 - for s in ./awk/*.awk; do ./scripts/validate.sh awk -f $s ./input && time awk -f $s ./input > /dev/null || $s Failed to pass the test; done
# - for s in ruby/*.rb; do ./script/validate.sh  

