language: ruby

addons:
  apt:
    packages:
     - time

before_script:
 - awk 'BEGIN{for (i=1;i<=10000000;i++) print (i%5?"miss":"hit"),i,"  third\t \tfourth"}' > ./input

script: 
 - ./scripts/build.sh
